version: '3'

services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/database-data:/var/lib/mysql 
    ports:
      - "33061:3306"
    networks:
      - iot-net

  broker:
    image: eclipse-mosquitto
    container_name: broker
    volumes:
      - ./broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./broker/broker-password/passwd:/mosquitto/passwd 
      - ./broker/certs:/mosquitto/config/certs
    ports:
      - "8883:8883"
      - "9001:9001"
    networks:
      - iot-net

  api:
    build: ./api
    container_name: api
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=iot
      - MQTT_BROKER=broker
    depends_on:
      - mysql
      - broker
    ports:
      - "8085:8080"
    networks:
      - iot-net
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - iot-net
    depends_on:
      - broker 

  ngrok-http:
    image: ngrok/ngrok:latest
    container_name: ngrok-http
    ports:
      - "4040:4040"
    command: http frontend:80
    environment:
      - NGROK_AUTHTOKEN=2uoojW4tEowyiUtQzfhtfw7y3Aj_4dsmEnZ5vMefyEfxX4Tmx
    depends_on:
      - frontend
    networks:
      - iot-net

  ngrok-tcp:
    image: ngrok/ngrok:latest
    container_name: ngrok-tcp
    command: tcp broker:8883
    ports:
      - "4041:4040"
    environment:
      - NGROK_AUTHTOKEN=2uoojW4tEowyiUtQzfhtfw7y3Aj_4dsmEnZ5vMefyEfxX4Tmx
    depends_on:
      - broker
    networks:
      - iot-net


volumes:
  database-data:

networks:
  iot-net:
    driver: bridge
